### ISSUE TITLE
Hiding "new Temporary container"-Icon

### ISSUE THREAD

**Issue by anonymous133** [stoically/temporary-containers#212]
Hi!

Is it possible to hide the top right icon somehow? I'm using only keyboard navigation and automatic mode, so the button is of no use to me and uses up space unnecessary.

Thank you!

**Comment by crssi** [comment]
Not directly in TC settings, but you can manipulate over userChrome.css
See about userChrome.css and where to find/create it here: https://fosspost.org/tutorials/how-to-customize-firefox-57-user-interface

If you insert the following into userChrome.css file, you will get the desired results:
``` css
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");

/* Remove Temporary Container icon */
toolbarbutton[label*='Temporary Container'] {
  display: none;
}
menuitem[label*='Open Link in New Temporary Container Tab'] {
  display: none;
}
#userContext-label {
  color: var(--toolbar-color) !important;
}
```

I have some more customizations, if you are interested.
You can find those in [my Firefox repository](https://github.com/crssi/Firefox)... see userChrome.css

Cheers
