### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by Puro00** [stoically/temporary-containers#283]
Hello

Can you please give Dark theme option for the addon?

**Comment by stoically** [comment]
SemanticUI, which is used for the options/popup, [supports theming](https://semantic-ui.com/usage/theming.html), but not Dark Mode out of the box, so this would require a fair amount of work.

**Comment by Puro00** [comment]
I will ask about Dark Theme support to them. Maybe they can add it.

**Comment by stoically** [comment]
I don't think that creating custom themes is in the scope of SUI.

**Comment by Puro00** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme Will help?

Some addons think use it

**Comment by stoically** [comment]
That's just for websites to detect whether a user visiting their page has dark mode enabled in their operating system.

**Comment by stoically** [comment]
Ah, you probably just meant it as a suggestion for to detect dark theme usage, yeah, sure, good idea!

**Comment by Thorin-Oakenpants** [comment]
FYI: RFP spoofs prefers-color-scheme as light

**Comment by stoically** [comment]
Closing in favour of [Quantum Nox](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme) which [supports TC](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#addon-dark-themes) - please use that if you want a dark theme.

**Comment by DrWhoCares** [comment]
In case anyone wanted to style this manually, using `userContent.css` tweaking, place this at the bottom of your userContent.css file in the `chrome` folder of your Firefox profile. You need to replace the part at the top of this code with your own internal UUID for the addon, which you can find by opening the options page, then copying the value after the `moz-extension://` and before the `options.html`. Replace the `RANDOM-STRING-OF-NUMBERS-AND-LETTERS` in the code below with your internal UUID.

Disclaimer, I threw this together rather quickly, and didn't spend much time making it very nice, nor am I a master at these tweaks. This may not work without using [ShadowFox](https://github.com/overdodactyl/ShadowFox).

```css
@-moz-document url-prefix("moz-extension://RANDOM-STRING-OF-NUMBERS-AND-LETTERS/") {
  body {
    background: #000!important;
    background-color: #000!important;
    color: #38383d!important;
  }
  span {
    color: #b1b1b3!important;
  }
  button {
    background-color: #38383d!important;
    border-color: #737373!important;
    color: #b1b1b3!important
  }
  .ui.menu,
  .ui.menu .item,
  .ui.tab,
  .ui.segment,
  .ui.form,
  .ui.selection,
  .ui.dropdown,
  .ui.accordion .title:not(.ui),
  .ui.form .field > label,
  .ui.checkbox label, .ui.checkbox + label,
  .ui.tabular.menu .active.item {
    -moz-appearance: none!important;
    background: #4a4a4f!important;
    color: #b1b1b3!important;
    border-color: #737373!important;
  }
  .ui.tabular.menu .active.item {
    background: #4a4a4f!important;
  }
  input[type=text],
  textarea {
    -moz-appearance: none!important;
    background: #4a4a4f!important;
    color: #b1b1b3!important;
    border: 1px solid!important;
    padding: 2px!important;
    border-color: #737373!important
  }
  input[type=text] {
    border-radius: 3px!important
  }
  .checkbox-check,
  label::before,
  .radio-check,
  input[type=checkbox] {
    -moz-appearance: none!important;
    border: 1px solid!important;
    background-color: #4a4a4f!important;
    background-image: none!important;
    box-shadow: none!important;
    border-color: #737373!important
  }
}
```

If you're using [ShadowFox](https://github.com/overdodactyl/ShadowFox) (which I highly recommend since that's what I used to do this) then you can use the code below.

```css
@-moz-document url-prefix("moz-extension://RANDOM-STRING-OF-NUMBERS-AND-LETTERS/") {
  body {
    background: black!important;
    background-color: black!important;
    color: var(--tone-7)!important;
  }
  span {
    color: var(--in-content-page-color)!important;
  }
  button {
    background-color: var(--in-content-page-background)!important;
    border-color: var(--in-content-box-border-color)!important;
    color: var(--in-content-page-color)!important
  }
  .ui.menu,
  .ui.menu .item,
  .ui.tab,
  .ui.segment,
  .ui.form,
  .ui.selection,
  .ui.dropdown,
  .ui.accordion .title:not(.ui),
  .ui.form .field > label,
  .ui.checkbox label, .ui.checkbox + label,
  .ui.tabular.menu .active.item {
    -moz-appearance: none!important;
    background: var(--in-content-box-background)!important;
    color: var(--in-content-page-color)!important;
    border-color: var(--in-content-box-border-color)!important;
  }
  .ui.tabular.menu .active.item {
    background: var(--in-content-box-background-active)!important;
  }
  input[type=text],
  textarea {
    -moz-appearance: none!important;
    background: var(--in-content-box-background)!important;
    color: var(--in-content-page-color)!important;
    border: 1px solid!important;
    padding: 2px!important;
    border-color: var(--in-content-box-border-color)!important
  }
  input[type=text] {
    border-radius: 3px!important
  }
  .checkbox-check,
  label::before,
  .radio-check,
  input[type=checkbox] {
    -moz-appearance: none!important;
    border: 1px solid!important;
    background-color: var(--in-content-box-background)!important;
    background-image: none!important;
    box-shadow: none!important;
    border-color: var(--in-content-box-border-color)!important
  }
}
```
